Iss hipcms 77 achievements
HiP-App/HiP-CmsAngularApp pull request #766
Opened 2018-02-11 08:40 UTC by ruchirnaphade

Create, edit and delete achievement with image
choose exhibit and choose route is not working as we need data regarding the same from server.

Kindly do not review old PR for achievements i.e. iss-hipangular-77-create-achievement-dialog

2018-03-10 10:40 UTC, pschick submitted a review, later dismissed
TODO:
- I can't select an exhibit in the dropdown when trying to create an "Exhibits visited" achievement
- The "With status" filter doesn't work when "In Review" is selected
- Restrict the file upload to the supported file types (e.g. png is not a supported file type)

2018-03-11 14:38 UTC, ruchirnaphade commented
- Removed select box from exhibit visited
- with status is not working because there is something wrong with backend. (asked michel and confirmed)
- Removed png type

2018-04-23 07:30 UTC, rajatkhanna1994 requested changes
When creating a new achievement, I'm not able to view it on the Achievements page. Only after refreshing it, I'm able to see the newly created achievement.
Could you look into it?

2018-04-23 11:12 UTC, rajatkhanna1994 approved these changes

2018-04-23 11:16 UTC, merged